FROM node:12.21.0

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install
RUN apt-get --assume-yes update
COPY .. .
COPY ../data_file ./data_file

CMD [ "node", "./data_file/data_file_loader.js" ]